In [1]:
import numpy as np
import pandas as pd

In [2]:
tren = pd.read_csv('data_1_col.csv')

In [3]:
tren.sum()

trending_date    26.26.0226.26.0226.26.0226.26.0226.26.0226.26....
Unnamed: 1                                                     0.0
Unnamed: 2                                                     0.0
dtype: object

In [ ]:
tren.median()

TypeError: Cannot perform reduction 'median' with string dtype

In [5]:
tren.max()

trending_date    26.26.02
Unnamed: 1            NaN
Unnamed: 2            NaN
dtype: object

In [6]:
tren.max()

trending_date    26.26.02
Unnamed: 1            NaN
Unnamed: 2            NaN
dtype: object

In [7]:
tren.min()

trending_date    26.26.02
Unnamed: 1            NaN
Unnamed: 2            NaN
dtype: object

In [8]:
tren.describe()

       Unnamed: 1  Unnamed: 2
count         0.0         0.0
mean          NaN         NaN
std           NaN         NaN
min           NaN         NaN
25%           NaN         NaN
50%           NaN         NaN
75%           NaN         NaN
max           NaN         NaN

In [9]:
tren[2:20:3]

   trending_date  Unnamed: 1  Unnamed: 2
2       26.26.02         NaN         NaN
5       26.26.02         NaN         NaN
8       26.26.02         NaN         NaN
11      26.26.02         NaN         NaN
14      26.26.02         NaN         NaN
17      26.26.02         NaN         NaN

In [ ]:
hi