In [15]:
rows = [ [1,2,3],[4,5,6],[7,8,9]]

In [16]:
import pandas as pd

In [17]:
lis = pd.DataFrame(rows,columns=['a','b','c'])
print(lis)

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [18]:
data = pd.read_csv("student_depression_dataset.csv")

In [19]:
print(data)

           id  Gender   Age           City Profession  Academic Pressure  \
0           2    Male  33.0  Visakhapatnam    Student                5.0
1           8  Female  24.0      Bangalore    Student                2.0
2          26    Male  31.0       Srinagar    Student                3.0
3          30  Female  28.0       Varanasi    Student                3.0
4          32  Female  25.0         Jaipur    Student                4.0
...       ...     ...   ...            ...        ...                ...
27896  140685  Female  27.0          Surat    Student                5.0
27897  140686    Male  27.0       Ludhiana    Student                2.0
27898  140689    Male  31.0      Faridabad    Student                3.0
27899  140690  Female  18.0       Ludhiana    Student                5.0
27900  140699    Male  27.0          Patna    Student                4.0

       Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  \
0                0.0  8.97                 2.0               0.0
1                0.0  5.90                 5.0               0.0
2                0.0  7.03                 5.0               0.0
3                0.0  5.59                 2.0               0.0
4                0.0  8.13                 3.0               0.0
...              ...   ...                 ...               ...
27896            0.0  5.75                 5.0               0.0
27897            0.0  9.40                 3.0               0.0
27898            0.0  6.61                 4.0               0.0
27899            0.0  6.88                 2.0               0.0
27900            0.0  9.24                 1.0               0.0

            Sleep Duration Dietary Habits      Degree  \
0              '5-6 hours'        Healthy     B.Pharm
1              '5-6 hours'       Moderate         BSc
2      'Less than 5 hours'        Healthy          BA
3              '7-8 hours'       Moderate         BCA
4              '5-6 hours'       Moderate      M.Tech
...                    ...            ...         ...
27896          '5-6 hours'      Unhealthy  'Class 12'
27897  'Less than 5 hours'        Healthy         MSc
27898          '5-6 hours'      Unhealthy          MD
27899  'Less than 5 hours'        Healthy  'Class 12'
27900  'Less than 5 hours'        Healthy         BCA

      Have you ever had suicidal thoughts ?  Work/Study Hours  \
0                                       Yes               3.0
1                                        No               3.0
2                                        No               9.0
3                                       Yes               4.0
4                                       Yes               1.0
...                                     ...               ...
27896                                   Yes               7.0
27897                                    No               0.0
27898                                    No              12.0
27899                                   Yes              10.0
27900                                   Yes               2.0

      Financial Stress Family History of Mental Illness  Depression
0                  1.0                               No           1
1                  2.0                              Yes           0
2                  1.0                              Yes           0
3                  5.0                              Yes           1
4                  1.0                               No           0
...                ...                              ...         ...
27896              1.0                              Yes           0
27897              3.0                              Yes           0
27898              2.0                               No           0
27899              5.0                               No           1
27900              3.0                              Yes           1

[27901 rows x 18 columns]

In [20]:
data

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,'Less than 5 hours',Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,'Less than 5 hours',Healthy,'Class 12',Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

In [21]:
data.shape

(27901, 18)

In [23]:
data.dtypes

id                                         int64
Gender                                       str
Age                                      float64
City                                         str
Profession                                   str
Academic Pressure                        float64
Work Pressure                            float64
CGPA                                     float64
Study Satisfaction                       float64
Job Satisfaction                         float64
Sleep Duration                               str
Dietary Habits                               str
Degree                                       str
Have you ever had suicidal thoughts ?        str
Work/Study Hours                         float64
Financial Stress                             str
Family History of Mental Illness             str
Depression                                 int64
dtype: object

In [24]:
data.size

502218

In [25]:
data.head(10)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
5,33,Male,29.0,Pune,Student,2.0,0.0,5.70,3.0,0.0,'Less than 5 hours',Healthy,PhD,No,4.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,'7-8 hours',Healthy,BSc,No,1.0,2.0,No,0
7,56,Female,30.0,Chennai,Student,2.0,0.0,8.04,4.0,0.0,'Less than 5 hours',Unhealthy,'Class 12',No,0.0,1.0,Yes,0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,'7-8 hours',Moderate,B.Ed,Yes,12.0,3.0,No,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,'Less than 5 hours',Moderate,LLB,Yes,2.0,5.0,No,1

In [26]:
data.sample

<bound method NDFrame.sample of            id  Gender   Age           City Profession  Academic Pressure  \
0           2    Male  33.0  Visakhapatnam    Student                5.0
1           8  Female  24.0      Bangalore    Student                2.0
2          26    Male  31.0       Srinagar    Student                3.0
3          30  Female  28.0       Varanasi    Student                3.0
4          32  Female  25.0         Jaipur    Student                4.0
...       ...     ...   ...            ...        ...                ...
27896  140685  Female  27.0          Surat    Student                5.0
27897  140686    Male  27.0       Ludhiana    Student                2.0
27898  140689    Male  31.0      Faridabad    Student                3.0
27899  140690  Female  18.0       Ludhiana    Student                5.0
27900  140699    Male  27.0          Patna    Student                4.0

       Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  \
0                0.0  8.97                 2.0               0.0
1                0.0  5.90                 5.0               0.0
2                0.0  7.03                 5.0               0.0
3                0.0  5.59                 2.0               0.0
4                0.0  8.13                 3.0               0.0
...              ...   ...                 ...               ...
27896            0.0  5.75                 5.0               0.0
27897            0.0  9.40                 3.0               0.0
27898            0.0  6.61                 4.0               0.0
27899            0.0  6.88                 2.0               0.0
27900            0.0  9.24                 1.0               0.0

            Sleep Duration Dietary Habits      Degree  \
0              '5-6 hours'        Healthy     B.Pharm
1              '5-6 hours'       Moderate         BSc
2      'Less than 5 hours'        Healthy          BA
3              '7-8 hours'       Moderate         BCA
4              '5-6 hours'       Moderate      M.Tech
...                    ...            ...         ...
27896          '5-6 hours'      Unhealthy  'Class 12'
27897  'Less than 5 hours'        Healthy         MSc
27898          '5-6 hours'      Unhealthy          MD
27899  'Less than 5 hours'        Healthy  'Class 12'
27900  'Less than 5 hours'        Healthy         BCA

      Have you ever had suicidal thoughts ?  Work/Study Hours  \
0                                       Yes               3.0
1                                        No               3.0
2                                        No               9.0
3                                       Yes               4.0
4                                       Yes               1.0
...                                     ...               ...
27896                                   Yes               7.0
27897                                    No               0.0
27898                                    No              12.0
27899                                   Yes              10.0
27900                                   Yes               2.0

      Financial Stress Family History of Mental Illness  Depression
0                  1.0                               No           1
1                  2.0                              Yes           0
2                  1.0                              Yes           0
3                  5.0                              Yes           1
4                  1.0                               No           0
...                ...                              ...         ...
27896              1.0                              Yes           0
27897              3.0                              Yes           0
27898              2.0                               No           0
27899              5.0                               No           1
27900              3.0                              Yes           1

[27901 rows x 18 columns]>

In [27]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  str
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  str
 4   Profession                             27901 non-null  str
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  str
 11  Dietary Habits                         27901 non-null  str
 12  Degree                                 27901 non-null  str
 13  Have you ever had suicidal thoughts ?  27901 non-null  str
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27901 non-null  str
 16  Family History of Mental Illness       27901 non-null  str
 17  Depression                             27901 non-null  int64
dtypes: float64(7), int64(2), str(9)
memory usage: 5.3 MB

In [28]:
data.describe()

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Depression
count,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000
mean,70442.149421,25.822300,3.141214,0.000430,7.656104,2.943837,0.000681,7.156984,0.585499
std,40641.175216,4.905687,1.381465,0.043992,1.470707,1.361148,0.044394,3.707642,0.492645
min,2.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,35039.000000,21.000000,2.000000,0.000000,6.290000,2.000000,0.000000,4.000000,0.000000
50%,70684.000000,25.000000,3.000000,0.000000,7.770000,3.000000,0.000000,8.000000,1.000000
75%,105818.000000,30.000000,4.000000,0.000000,8.920000,4.000000,0.000000,10.000000,1.000000
max,140699.000000,59.000000,5.000000,5.000000,10.000000,5.000000,4.000000,12.000000,1.000000