In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("student_depression_dataset.csv")

In [3]:
df.isnull()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27897,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27898,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27899,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27900,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [4]:
df.isnull().sum()

id                                       0
Gender                                   0
Age                                      0
City                                     0
Profession                               0
Academic Pressure                        0
Work Pressure                            0
CGPA                                     0
Study Satisfaction                       0
Job Satisfaction                         0
Sleep Duration                           0
Dietary Habits                           0
Degree                                   0
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         0
Family History of Mental Illness         0
Depression                               0
dtype: int64

In [7]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
27896    False
27897    False
27898    False
27899    False
27900    False
Length: 27901, dtype: bool

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.rename(columns={'CGPA':'cgpa','Age':'Student_Age'})

,id,Gender,Student_Age,City,Profession,Academic Pressure,Work Pressure,cgpa,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,'Less than 5 hours',Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,'Less than 5 hours',Healthy,'Class 12',Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

In [11]:
df.sum()

id                                                                              1965406411
Gender                                   MaleFemaleMaleFemaleFemaleMaleMaleFemaleMaleMa...
Age                                                                               720468.0
City                                     VisakhapatnamBangaloreSrinagarVaranasiJaipurPu...
Profession                               StudentStudentStudentStudentStudentStudentStud...
Academic Pressure                                                                  87643.0
Work Pressure                                                                         12.0
CGPA                                                                           213612.9625
Study Satisfaction                                                                 82136.0
Job Satisfaction                                                                      19.0
Sleep Duration                           '5-6 hours''5-6 hours''Less than 5 hours''7-8 ...
Dietary Habits                           HealthyModerateHealthyModerateModerateHealthyH...
Degree                                   B.PharmBScBABCAM.TechPhDBSc'Class 12'B.EdLLB'C...
Have you ever had suicidal thoughts ?    YesNoNoYesYesNoNoNoYesYesYesYesNoNoYesYesYesYe...
Work/Study Hours                                                                  199687.0
Financial Stress                         1.02.01.05.01.01.02.01.03.05.01.02.01.02.05.02...
Family History of Mental Illness         NoYesYesYesNoNoNoYesNoNoYesYesYesYesYesYesYesN...
Depression                                                                           16336
dtype: object

In [12]:
df.values[1]

array([8, 'Female', 24.0, 'Bangalore', 'Student', 2.0, 0.0, 5.9, 5.0, 0.0,
       "'5-6 hours'", 'Moderate', 'BSc', 'No', 3.0, '2.0', 'Yes', 0],
      dtype=object)

In [14]:
df.sum(axis=0)

id                                                                              1965406411
Gender                                   MaleFemaleMaleFemaleFemaleMaleMaleFemaleMaleMa...
Age                                                                               720468.0
City                                     VisakhapatnamBangaloreSrinagarVaranasiJaipurPu...
Profession                               StudentStudentStudentStudentStudentStudentStud...
Academic Pressure                                                                  87643.0
Work Pressure                                                                         12.0
CGPA                                                                           213612.9625
Study Satisfaction                                                                 82136.0
Job Satisfaction                                                                      19.0
Sleep Duration                           '5-6 hours''5-6 hours''Less than 5 hours''7-8 ...
Dietary Habits                           HealthyModerateHealthyModerateModerateHealthyH...
Degree                                   B.PharmBScBABCAM.TechPhDBSc'Class 12'B.EdLLB'C...
Have you ever had suicidal thoughts ?    YesNoNoYesYesNoNoNoYesYesYesYesNoNoYesYesYesYe...
Work/Study Hours                                                                  199687.0
Financial Stress                         1.02.01.05.01.01.02.01.03.05.01.02.01.02.05.02...
Family History of Mental Illness         NoYesYesYesNoNoNoYesNoNoYesYesYesYesYesYesYesN...
Depression                                                                           16336
dtype: object

In [16]:
df.min(axis=1)

TypeError: '<=' not supported between instances of 'int' and 'str'

In [ ]:
df.max()

id                                              140699
Gender                                            Male
Age                                               59.0
City                                     Visakhapatnam
Profession                                     Teacher
Academic Pressure                                  5.0
Work Pressure                                      5.0
CGPA                                              10.0
Study Satisfaction                                 5.0
Job Satisfaction                                   4.0
Sleep Duration                                  Others
Dietary Habits                               Unhealthy
Degree                                             PhD
Have you ever had suicidal thoughts ?              Yes
Work/Study Hours                                  12.0
Financial Stress                                     ?
Family History of Mental Illness                   Yes
Depression                                           1
dtype: object

In [18]:
df.index

RangeIndex(start=0, stop=27901, step=1)

In [19]:
df.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [20]:
df['Age']

0        33.0
1        24.0
2        31.0
3        28.0
4        25.0
         ...
27896    27.0
27897    27.0
27898    31.0
27899    18.0
27900    27.0
Name: Age, Length: 27901, dtype: float64

In [21]:
df.iloc[10]

id                                                83
Gender                                          Male
Age                                             24.0
City                                          Nagpur
Profession                                   Student
Academic Pressure                                3.0
Work Pressure                                    0.0
CGPA                                             6.1
Study Satisfaction                               3.0
Job Satisfaction                                 0.0
Sleep Duration                           '5-6 hours'
Dietary Habits                              Moderate
Degree                                    'Class 12'
Have you ever had suicidal thoughts ?            Yes
Work/Study Hours                                11.0
Financial Stress                                 1.0
Family History of Mental Illness                 Yes
Depression                                         1
Name: 10, dtype: object

In [22]:
df.iloc[::2]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,'7-8 hours',Healthy,BSc,No,1.0,2.0,No,0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,'7-8 hours',Moderate,B.Ed,Yes,12.0,3.0,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27892,140669,Female,20.0,Indore,Student,3.0,0.0,7.72,5.0,0.0,'Less than 5 hours',Moderate,'Class 12',Yes,8.0,1.0,No,0
27894,140681,Male,23.0,Srinagar,Student,3.0,0.0,6.00,2.0,0.0,'More than 8 hours',Healthy,MBBS,Yes,12.0,4.0,No,0
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

In [23]:
df[::2]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,'7-8 hours',Healthy,BSc,No,1.0,2.0,No,0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,'7-8 hours',Moderate,B.Ed,Yes,12.0,3.0,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27892,140669,Female,20.0,Indore,Student,3.0,0.0,7.72,5.0,0.0,'Less than 5 hours',Moderate,'Class 12',Yes,8.0,1.0,No,0
27894,140681,Male,23.0,Srinagar,Student,3.0,0.0,6.00,2.0,0.0,'More than 8 hours',Healthy,MBBS,Yes,12.0,4.0,No,0
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1